<?php
// 确保没有输出缓冲
if (ob_get_level()) ob_end_clean();

// 设置正确的Content-Type
header('Content-Type: application/xml; charset=utf-8');

// 确保没有其他输出
ob_clean();

// 输出XML声明
echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <!-- 主页 -->
    <url>
        <loc>https://sonice.online/</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
    </url>
    
    <!-- 分类页面 -->
    <url>
        <loc>https://sonice.online/category/action</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/racing</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/sports</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/shooter</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/cards</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/adventure</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/puzzle</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/strategy</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/mining</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/idle</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/clicker</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/simulation</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/tycoon</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/arcade</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/board</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/platformer</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/multiplayer</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/io</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/music</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/educational</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://sonice.online/category/other</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    
    <!-- 静态页面 -->
    <url>
        <loc>https://sonice.online/about</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://sonice.online/contact</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.6</priority>
    </url>
    <url>
        <loc>https://sonice.online/privacy</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>https://sonice.online/terms</loc>
        <lastmod>2024-08-06</lastmod>
        <changefreq>monthly</changefreq>
        <priority>0.5</priority>
    </url>
</urlset> 